export const emmaConfigNames = [
  '.emmarc',
  '.emmarc.json',
  'emma.json',
  // 'package.json',
  // 'emma.config.js',
]

export const emmaSetupBranchHead = 'emma/setup'

export const setupPullRequestTemplate = `
# Emma Boilerplates

> This is an autogenerated pull request.

We are happy to see you decided to use Emma Boilerplates.
This PR is a means of communication where we'll post updates about
the status of your repository.

Let us know if you need any extra help by openning an issue on
https://github.com/maticzav/emma
`

export const missingConfigurationMessage = `
We haven't found any configuration in this repository.

To use Emma boilerplates add emma.json file to root of repository.
Otherwise, you can ignore this pull request thoroughly.
`
